"""initial_schema

Revision: 79efb64b06fc
"""

from alembic import op
import sqlalchemy as sa


revision = "79efb64b06fc"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "change_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("component", sa.String(length=120), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("actor", sa.String(length=120), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "datasets",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("layer", sa.String(length=24), nullable=False),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.Column("owner", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("critical", sa.Boolean(), nullable=False),
        sa.Column("health", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("latest_run_id", sa.String(length=40), nullable=True),
        sa.Column("last_materialized", sa.String(length=40), nullable=True),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "job_leases",
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("owner", sa.String(length=40), nullable=False),
        sa.Column("expires_at", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "pipeline_runs",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("idempotency_key", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("trigger", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.String(length=40), nullable=False),
        sa.Column("completed_at", sa.String(length=40), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("records", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("stages", sa.JSON(), nullable=False),
        sa.Column("synthetic", sa.Boolean(), nullable=False),
        sa.Column("scenario", sa.String(length=40), nullable=True),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    with op.batch_alter_table("pipeline_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_pipeline_runs_status"), ["status"], unique=False)
        batch_op.create_index("ix_runs_started", ["started_at"], unique=False)

    op.create_table(
        "product_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=60), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "workspace_state",
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "anomalies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dataset_id", sa.String(length=80), nullable=False),
        sa.Column("run_id", sa.String(length=40), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("column", sa.String(length=80), nullable=True),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("observed", sa.Float(), nullable=True),
        sa.Column("expected", sa.Text(), nullable=False),
        sa.Column("method", sa.String(length=100), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["pipeline_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dataset_id", "run_id", "kind", "column"),
    )
    with op.batch_alter_table("anomalies", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_anomalies_dataset_id"), ["dataset_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_anomalies_run_id"), ["run_id"], unique=False)

    op.create_table(
        "dataset_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dataset_id", sa.String(length=80), nullable=False),
        sa.Column("run_id", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("column_count", sa.Integer(), nullable=False),
        sa.Column("duplicate_rate", sa.Float(), nullable=False),
        sa.Column("health", sa.Float(), nullable=True),
        sa.Column("schema", sa.JSON(), nullable=False),
        sa.Column("columns", sa.JSON(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("health_components", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["pipeline_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dataset_id", "run_id"),
    )
    with op.batch_alter_table("dataset_profiles", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_dataset_profiles_dataset_id"), ["dataset_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_dataset_profiles_run_id"), ["run_id"], unique=False)

    op.create_table(
        "incidents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("root_dataset_id", sa.String(length=80), nullable=False),
        sa.Column("root_score", sa.Float(), nullable=False),
        sa.Column("owner", sa.String(length=120), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.Column("updated_at", sa.String(length=40), nullable=False),
        sa.Column("resolved_at", sa.String(length=40), nullable=True),
        sa.Column("healthy_runs", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["root_dataset_id"],
            ["datasets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("incidents", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_incidents_status"), ["status"], unique=False)

    op.create_table(
        "lineage_edges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.String(length=80), nullable=False),
        sa.Column("target_id", sa.String(length=80), nullable=False),
        sa.Column("transformation", sa.String(length=120), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["datasets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["datasets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "target_id"),
    )
    op.create_table(
        "quality_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dataset_id", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("column", sa.String(length=80), nullable=True),
        sa.Column("params", sa.JSON(), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("quality_rules", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_quality_rules_dataset_id"), ["dataset_id"], unique=False)

    op.create_table(
        "evidence",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("incident_id", sa.Integer(), nullable=False),
        sa.Column("anomaly_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("facts", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["anomaly_id"],
            ["anomalies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("anomaly_id"),
    )
    with op.batch_alter_table("evidence", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_evidence_incident_id"), ["incident_id"], unique=False)

    op.create_table(
        "incident_anomalies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("incident_id", sa.Integer(), nullable=False),
        sa.Column("anomaly_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["anomaly_id"],
            ["anomalies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("anomaly_id"),
    )
    with op.batch_alter_table("incident_anomalies", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_incident_anomalies_incident_id"), ["incident_id"], unique=False)

    op.create_table(
        "incident_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("incident_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("incident_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_incident_events_incident_id"), ["incident_id"], unique=False)

    op.create_table(
        "investigations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("incident_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("report", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("investigations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_investigations_incident_id"), ["incident_id"], unique=False)

    op.create_table(
        "quality_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("rule_id", sa.Integer(), nullable=False),
        sa.Column("rule_version", sa.Integer(), nullable=False),
        sa.Column("dataset_id", sa.String(length=80), nullable=False),
        sa.Column("run_id", sa.String(length=40), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("observed", sa.Float(), nullable=False),
        sa.Column("expected", sa.Text(), nullable=False),
        sa.Column("failed_count", sa.Integer(), nullable=False),
        sa.Column("sample", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["quality_rules.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["pipeline_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("rule_id", "run_id"),
    )
    with op.batch_alter_table("quality_results", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_quality_results_dataset_id"), ["dataset_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_quality_results_run_id"), ["run_id"], unique=False)

    op.create_table(
        "quality_rule_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("rule_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("definition", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["quality_rules.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("rule_id", "version"),
    )
    op.create_table(
        "root_cause_candidates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("incident_id", sa.Integer(), nullable=False),
        sa.Column("dataset_id", sa.String(length=80), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("contributions", sa.JSON(), nullable=False),
        sa.Column("evidence_ids", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("incident_id", "dataset_id"),
    )
    with op.batch_alter_table("root_cause_candidates", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_root_cause_candidates_incident_id"), ["incident_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("root_cause_candidates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_root_cause_candidates_incident_id"))

    op.drop_table("root_cause_candidates")
    op.drop_table("quality_rule_versions")
    with op.batch_alter_table("quality_results", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_quality_results_run_id"))
        batch_op.drop_index(batch_op.f("ix_quality_results_dataset_id"))

    op.drop_table("quality_results")
    with op.batch_alter_table("investigations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_investigations_incident_id"))

    op.drop_table("investigations")
    with op.batch_alter_table("incident_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_incident_events_incident_id"))

    op.drop_table("incident_events")
    with op.batch_alter_table("incident_anomalies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_incident_anomalies_incident_id"))

    op.drop_table("incident_anomalies")
    with op.batch_alter_table("evidence", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_evidence_incident_id"))

    op.drop_table("evidence")
    with op.batch_alter_table("quality_rules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_quality_rules_dataset_id"))

    op.drop_table("quality_rules")
    op.drop_table("lineage_edges")
    with op.batch_alter_table("incidents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_incidents_status"))

    op.drop_table("incidents")
    with op.batch_alter_table("dataset_profiles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dataset_profiles_run_id"))
        batch_op.drop_index(batch_op.f("ix_dataset_profiles_dataset_id"))

    op.drop_table("dataset_profiles")
    with op.batch_alter_table("anomalies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_anomalies_run_id"))
        batch_op.drop_index(batch_op.f("ix_anomalies_dataset_id"))

    op.drop_table("anomalies")
    op.drop_table("workspace_state")
    op.drop_table("product_events")
    with op.batch_alter_table("pipeline_runs", schema=None) as batch_op:
        batch_op.drop_index("ix_runs_started")
        batch_op.drop_index(batch_op.f("ix_pipeline_runs_status"))

    op.drop_table("pipeline_runs")
    op.drop_table("job_leases")
    op.drop_table("datasets")
    op.drop_table("change_events")
    # ### end Alembic commands ###
