import { createContext, useContext, useEffect, useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import {
  Activity,
  ArrowUpRight,
  BookOpen,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  Database,
  FlaskConical,
  Gauge,
  GitBranch,
  Layers3,
  ListChecks,
  LoaderCircle,
  LogOut,
  Menu,
  Network,
  Play,
  Search,
  Settings2,
  ShieldCheck,
  X,
} from 'lucide-react';
import { api, ApiError } from './api';
import { Button, Logo, State } from './components';
import { OverviewView, DatasetsView, DatasetView } from './DatasetViews';
import { IncidentsView, IncidentView } from './IncidentViews';
import { LineageView } from './LineageView';
import {
  PipelinesView,
  RulesView,
  SourcesView,
  SimulatorView,
  ActivityView,
  SettingsView,
} from './OperationsViews';

interface WorkspaceContext {
  act: (label: string, job: () => Promise<unknown>) => Promise<boolean>;
  busy: string;
  go: (path: string) => void;
}
const Workspace = createContext<WorkspaceContext>({ act: async () => false, busy: '', go: () => {} });
export const useWorkspace = () => useContext(Workspace);

const navigation = [
  { id: 'overview', label: 'Overview', icon: Gauge },
  { id: 'datasets', label: 'Datasets', icon: Database },
  { id: 'lineage', label: 'Lineage', icon: Network },
  { id: 'incidents', label: 'Incidents', icon: Activity },
  { id: 'pipelines', label: 'Pipelines', icon: GitBranch },
  { id: 'rules', label: 'Quality rules', icon: ListChecks },
  { id: 'sources', label: 'Sources', icon: Layers3 },
];

function Login({ onSuccess }: { onSuccess: () => void }) {
  const [email, setEmail] = useState('admin@datapolice.local'),
    [password, setPassword] = useState(''),
    [error, setError] = useState(''),
    [busy, setBusy] = useState(false);
  async function submit(event: React.FormEvent) {
    event.preventDefault();
    setBusy(true);
    setError('');
    try {
      await api('/auth/login', 'POST', { email, password });
      onSuccess();
    } catch (e) {
      setError((e as Error).message);
    } finally {
      setBusy(false);
    }
  }
  return (
    <div className="login-page">
      <div className="login-story">
        <div className="brand">
          <Logo />
          <span>
            Data Police<span className="wordmark-dot">.</span>
          </span>
        </div>
        <div className="login-message">
          <span className="eyebrow light">THE DATA RELIABILITY WORKSPACE</span>
          <h1>
            Know what changed.
            <br />
            Follow the evidence.
          </h1>
          <p>A clear view of your data, from the first source to the last downstream dependency.</p>
          <div className="login-pill">
            <ShieldCheck size={19} />
            Your data. Your infrastructure.
          </div>
        </div>
        <div className="login-footer">
          Evidence-first investigation <span>Version 0.1</span>
        </div>
      </div>
      <div className="login-form-side">
        <form onSubmit={submit}>
          <div className="eyebrow">NORTHSTAR RETAIL</div>
          <h2>Welcome to your workspace</h2>
          <p>Sign in to monitor your data estate.</p>
          <label>
            Email address
            <input
              autoComplete="username"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              type="email"
              required
            />
          </label>
          <label>
            Password
            <input
              autoComplete="current-password"
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              required
            />
          </label>
          {error && (
            <div className="inline-error" role="alert">
              {error}
            </div>
          )}
          <Button primary disabled={busy} type="submit">
            {busy ? <LoaderCircle size={17} className="spin" /> : 'Sign in'}
            <ArrowUpRight size={17} />
          </Button>
          <p className="login-help">
            Use the credentials generated by the setup command.
            <br />
            This self-hosted workspace has no external sign-in service.
          </p>
          <div className="sandbox-label">
            <FlaskConical size={14} />
            Sandbox environment · Synthetic retail data
          </div>
        </form>
      </div>
    </div>
  );
}

export default function App() {
  const client = useQueryClient(),
    [route, setRoute] = useState(location.hash.slice(1) || 'overview'),
    [busy, setBusy] = useState(''),
    [toast, setToast] = useState<{ text: string; error?: boolean } | null>(null),
    [connected, setConnected] = useState(false),
    [sidebar, setSidebar] = useState(false),
    [search, setSearch] = useState('');
  const me = useQuery({ queryKey: ['me'], queryFn: () => api<{ email: string }>('/auth/me'), retry: false });
  const [section, id] = route.split('/');
  const go = (path: string) => {
    location.hash = path;
    setSidebar(false);
  };
  useEffect(() => {
    const callback = () => {
      setRoute(location.hash.slice(1) || 'overview');
      window.scrollTo(0, 0);
    };
    window.addEventListener('hashchange', callback);
    return () => window.removeEventListener('hashchange', callback);
  }, []);
  useEffect(() => {
    if (!toast) return;
    const timer = setTimeout(() => setToast(null), 5500);
    return () => clearTimeout(timer);
  }, [toast]);
  useEffect(() => {
    if (!me.data) return;
    const events = new EventSource('/api/events');
    let timer: ReturnType<typeof setTimeout> | undefined;
    events.onopen = () => setConnected(true);
    events.onerror = () => setConnected(false);
    events.addEventListener('update', () => {
      clearTimeout(timer);
      timer = setTimeout(() => client.invalidateQueries({ predicate: (q) => q.queryKey[0] !== 'me' }), 250);
    });
    return () => {
      clearTimeout(timer);
      events.close();
      setConnected(false);
    };
  }, [me.data, client]);
  async function act(label: string, job: () => Promise<unknown>) {
    if (busy) return false;
    setBusy(label);
    try {
      await job();
      await client.invalidateQueries({ predicate: (q) => q.queryKey[0] !== 'me' });
      setToast({ text: label });
      return true;
    } catch (e) {
      if (e instanceof ApiError && e.status === 401) client.invalidateQueries({ queryKey: ['me'] });
      setToast({ text: (e as Error).message, error: true });
      return false;
    } finally {
      setBusy('');
    }
  }
  if (me.isPending) return <State title="Opening Data Police" />;
  if (me.error && !(me.error instanceof ApiError && me.error.status === 401))
    return <State error={me.error} />;
  if (!me.data) return <Login onSuccess={() => client.invalidateQueries({ queryKey: ['me'] })} />;
  const title =
    navigation.find((n) => n.id === section)?.label ||
    { simulator: 'Failure lab', activity: 'Activity log', settings: 'Workspace settings' }[section] ||
    'Overview';
  let view;
  switch (section) {
    case 'datasets':
      view = id ? <DatasetView id={id} /> : <DatasetsView search={search} setSearch={setSearch} />;
      break;
    case 'incidents':
      view = id ? <IncidentView id={Number(id)} /> : <IncidentsView />;
      break;
    case 'lineage':
      view = <LineageView focus={id} />;
      break;
    case 'pipelines':
      view = <PipelinesView />;
      break;
    case 'rules':
      view = <RulesView />;
      break;
    case 'sources':
      view = <SourcesView />;
      break;
    case 'simulator':
      view = <SimulatorView />;
      break;
    case 'activity':
      view = <ActivityView />;
      break;
    case 'settings':
      view = <SettingsView />;
      break;
    default:
      view = <OverviewView />;
  }
  return (
    <Workspace.Provider value={{ act, busy, go }}>
      <div className="app-shell">
        {sidebar && (
          <button
            className="sidebar-backdrop"
            aria-label="Close navigation"
            onClick={() => setSidebar(false)}
          />
        )}
        <aside className={'sidebar ' + (sidebar ? 'is-open' : '')}>
          <a className="brand" href="#overview">
            <Logo />
            <span>
              Data Police<span className="wordmark-dot">.</span>
            </span>
          </a>
          <button className="workspace-switch" onClick={() => go('settings')}>
            <span className="workspace-avatar">N</span>
            <span>
              <strong>Northstar Retail</strong>
              <small>Sandbox workspace</small>
            </span>
            <ChevronDown size={15} />
          </button>
          <div className="nav-section">WORKSPACE</div>
          <nav aria-label="Main navigation">
            {navigation.map(({ id: navId, label, icon: Icon }) => (
              <a
                key={navId}
                className={'nav-link ' + (navId === section ? 'active' : '')}
                href={'#' + navId}
                onClick={() => setSidebar(false)}
              >
                <Icon size={18} />
                <span>{label}</span>
                {navId === section && <span className="nav-active-mark" />}
              </a>
            ))}
          </nav>
          <div className="nav-section">OPERATIONS</div>
          <nav aria-label="Operations">
            {[
              { id: 'simulator', label: 'Failure lab', icon: FlaskConical },
              { id: 'activity', label: 'Activity log', icon: BookOpen },
            ].map(({ id: navId, label, icon: Icon }) => (
              <a
                key={navId}
                href={'#' + navId}
                className={'nav-link ' + (navId === section ? 'active' : '')}
                onClick={() => setSidebar(false)}
              >
                <Icon size={18} />
                {label}
                {navId === 'simulator' && <span className="nav-tag">LAB</span>}
              </a>
            ))}
          </nav>
          <div className="sidebar-bottom">
            <div className="workspace-note">
              <ShieldCheck size={19} />
              <p>
                Evidence, not guesswork.<span>Every finding has a source.</span>
              </p>
            </div>
            <a href="#settings" className={'nav-link ' + (section === 'settings' ? 'active' : '')}>
              <Settings2 size={18} />
              Settings
            </a>
            <div className="account">
              <span className="account-avatar">AD</span>
              <div>
                <strong>Administrator</strong>
                <small>{me.data.email}</small>
              </div>
              <button
                className="icon-button"
                aria-label="Sign out"
                onClick={() =>
                  act('Signed out', async () => {
                    await api('/auth/logout', 'POST');
                    client.clear();
                    location.reload();
                  })
                }
              >
                <LogOut size={17} />
              </button>
            </div>
          </div>
        </aside>
        <div className="main-shell">
          <header className="topbar">
            <div className="breadcrumbs">
              <button
                className="icon-button mobile-menu"
                aria-label="Open navigation"
                onClick={() => setSidebar(true)}
              >
                <Menu size={21} />
              </button>
              <span>Workspace</span>
              <ChevronRight size={14} />
              <strong>{title}</strong>
              {id && (
                <>
                  <ChevronRight size={14} />
                  <span className="crumb-detail">
                    {section === 'incidents' ? 'DP-' + (Number(id) + 1000) : id}
                  </span>
                </>
              )}
            </div>
            <div className="top-actions">
              <label className="global-search">
                <Search size={16} />
                <input
                  aria-label="Search datasets"
                  placeholder="Search datasets..."
                  value={search}
                  onChange={(e) => {
                    setSearch(e.target.value);
                    if (section !== 'datasets' || id) go('datasets');
                  }}
                />
                <kbd>/</kbd>
              </label>
              <span className="env-pill">
                <FlaskConical size={13} />
                Sandbox
              </span>
              <span className="top-avatar">AD</span>
            </div>
          </header>
          <main>{view}</main>
          <footer className="app-footer">
            <span>
              <span className={'connection-dot ' + (connected ? 'connected' : '')} />
              {connected ? 'Live updates connected' : 'Reconnecting live updates'}
              <span className="sep">·</span>Data Police v0.1
            </span>
            <span>
              Synthetic retail data <span className="sep">/</span> Your infrastructure
            </span>
          </footer>
        </div>
        {busy && (
          <div className="working-pill" role="status">
            <LoaderCircle size={15} className="spin" />
            Working...
          </div>
        )}
        {toast && (
          <div className={'toast ' + (toast.error ? 'toast-error' : '')} role="status">
            {toast.error ? <X size={18} /> : <CheckCircle2 size={18} />}
            <span>{toast.text}</span>
            <button onClick={() => setToast(null)} aria-label="Dismiss notification">
              <X size={15} />
            </button>
          </div>
        )}
      </div>
    </Workspace.Provider>
  );
}

export function RunButton() {
  const { act, busy } = useWorkspace();
  return (
    <Button primary disabled={!!busy} onClick={() => act('Pipeline run queued', () => api('/runs', 'POST'))}>
      <Play size={15} />
      Run pipeline
    </Button>
  );
}
